cp List-Stub.txt lst-list-stack-new.sh
cp List-Stub.txt lst-list-stack-push.sh
cp List-Stub.txt lst-list-stack-pop.sh
cp List-Stub.txt lst-list-stack-top.sh
cp List-Stub.txt lst-list-stack-empty.sh
cp List-Stub.txt lst-list-stack-rm.sh
cp List-Stub.txt lst-list-stack-size.sh
cp List-Stub.txt lst-list-stack-type.sh
cp List-Stub.txt lst-list-queue-new.sh
cp List-Stub.txt lst-list-queue-push.sh
cp List-Stub.txt lst-list-queue-pop.sh
cp List-Stub.txt lst-list-queue-top.sh
cp List-Stub.txt lst-list-queue-empty.sh
cp List-Stub.txt lst-ist-queue-rm.sh
cp List-Stub.txt lst-list-queue-size.sh
cp List-Stub.txt lst-list-queue-type.sh
cp List-Stub.txt lst-list-deque-new.sh
cp List-Stub.txt lst-list-deque-head-push.sh
cp List-Stub.txt lst-list-deque-head-pop.sh
cp List-Stub.txt lst-list-deque-head-top.sh
cp List-Stub.txt lst-list-deque-tail-push.sh
cp List-Stub.txt lst-list-deque-tail-pop.sh
cp List-Stub.txt lst-list-deque-tail-top.sh
cp List-Stub.txt lst-list-deque-empty.sh
cp List-Stub.txt lst-list-deque-rm.sh
cp List-Stub.txt lst-list-deque-size.sh
cp List-Stub.txt lst-list-deque-type.sh
